name: Python application

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:

    runs-on: ubuntu-latest
    env:
      Username: ${{ secrets.USERNAME }}
      Password: ${{ secrets.PASSWORD }}
      UserAgent: ${{ secrets.USERAGENT }}
      cID: ${{ secrets.CID }}
      cSC: ${{ secrets.CSC }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install praw
    - name: Test with pytest
      run: |
        python3 Version1.1/DochBotv1.1.py Username $username Password $password UserAgent $useragent cID $cid cSC $csc
